server:
  port: 8081
spring:
  application:
    name: customer-service
eureka:
  client:
    service-url:
      defaultZon: http://localhost:8761/eureka

#hystrix ?????????????
feign:
  hystrix:
    enabled: true
